version: 2

updates:
  - package-ecosystem: "bun"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "daily"

    groups:
      bun-minor-patch:
        update-types:
          - "minor"
          - "patch"

      bun-security:
        applies-to: security-updates
        patterns:
          - "*"
